---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(skimr)
```

```{r}
labour_prod <- read_csv("raw_data/labour_prod.csv") %>% 
  clean_names()

multifactor_prod <- read_excel("raw_data/multifactor_prod.xls") %>% 
  clean_names()

capital_prod <- read_csv("raw_data/capital_productivity.csv") %>% 
  clean_names()
```
###filter so that we're using the same countries as other datasets
```{r}
bop_clean <- read_csv("clean_data/bop_clean.csv")

developed_codes <- unique(bop_clean$country_code)

labour_prod <- labour_prod %>% 
  filter(location %in% developed_codes)

#multifactor productivity is only OECD countries, all of which are in my criteria of developed countries
```
```{r}
capital_prod <- capital_prod %>% 
  filter(location != omit & subject_2 == "Total capital services")
```

```{r}
multifactor_prod <- multifactor_prod %>% 
  filter(location %in% developed_codes & measure == "AGRWTH")
```

###remove and rename rows
```{r}
labour_prod  <- labour_prod %>% 
  select(-c(indicator, subject, measure, frequency, flag_codes)) %>%
  rename(gdp_hr_worked = value) %>% 
  mutate(date = make_date(time)) %>% 
  select(-time)
```

```{r}
multifactor_prod <- multifactor_prod %>% 
  select(-c(indicator, subject, measure, frequency, flag_codes)) %>%
  rename(multifactor_prod_agrwth = value) %>% 
  mutate(date = make_date(time)) %>% 
  select(-time)
```

```{r}
capital_prod <- capital_prod %>% 
  mutate(date = make_date(time)) %>% 
  select(c(location, date, value)) %>% 
  rename(capital_services_pc_growth = value)
```
###factors affecting productivity
```{r}
adult_education <- read_excel("raw_data/adult_education_levels.xlsx") %>% 
  clean_names()

tertiary_spending <- read_excel("raw_data/tertiary_spending.xlsx") %>% 
  clean_names()

infastructure_spending <- read_excel("raw_data/infastructure_investment.xls") %>% 
  clean_names()

flexible_working <- read_excel("raw_data/part_time_employment.xls") %>% 
  row_to_names(row_number = 3) %>% 
  clean_names() %>% 
  rename_all(~stringr::str_replace_all(.,"x", "" ))

r_d_spending <- read_excel("raw_data/research_and_development.xls") %>% 
  row_to_names(row_number = 3) %>% 
  clean_names() %>% 
  rename_all(~stringr::str_replace_all(.,"x", "" ))

trade_unions <- read_excel("raw_data/trade_union.xlsx") %>% 
  row_to_names(row_number = 5) %>% 
  clean_names() %>% 
  rename("country" = "year") %>% 
  rename_all(~stringr::str_replace_all(.,"x", "" ))

wages <- read_excel("raw_data/wages.xlsx") %>% 
  clean_names()

tech_adoption <- read_excel("raw_data/tech_adoption.xls", sheet = 5)

unemployment <- read_excel("raw_data/unemployment.xls") %>% 
    row_to_names(row_number = 3) %>% 
  clean_names() %>% 
  rename_all(~stringr::str_replace_all(.,"x", "" ))

business_ease <- read_excel("raw_data/ease_of_business.xlsx") %>% 
  clean_names()

openness <- read_excel("raw_data/economic_openness.xlsx") %>% 
  clean_names()

competitiveness <- read_excel("raw_data/competitiveness_index.xlsx", sheet = 2) %>% 
  row_to_names(row_number = 3) 
```

```{r}
adult_education <- adult_education %>% 
  filter(location %in% developed_codes) %>% 
  select(location, time, value) %>% 
  rename(adult_education_pc = value) %>% 
  mutate(date = make_date(time)) %>% 
  select(-time)

tertiary_spending <- tertiary_spending %>% 
  filter(location %in% developed_codes) %>% 
  select(location, time, value) %>% 
  rename(education_spending_pc = value) %>% 
  mutate(date = make_date(time)) %>% 
  select(-time)
```

```{r}
infastructure_spending <- infastructure_spending %>% 
  filter(location %in% developed_codes & subject %in% c("ROAD", "RAIL")) %>%
  pivot_wider(values_from = value, names_from = subject) %>% 
  mutate(transport_investment_eur = `RAIL` + `ROAD`) %>% 
  select(location, time, transport_investment_eur) %>% 
   mutate(date = make_date(time)) %>% 
  select(-time)
```
```{r}
r_d_spending <- r_d_spending %>% 
  filter(country_code %in% developed_codes) %>% 
  pivot_longer("1960":"2021", names_to = "time", 
               values_to = "r_and_d_spending_pc") %>% 
  select(time, country_code, r_and_d_spending_pc) %>% 
   mutate(date = make_date(time)) %>% 
  select(-time)
```
```{r}
trade_unions <- trade_unions %>% 
  filter(country %in% developed_countries |
           country == "United Kingdom") %>% 
  mutate(across(starts_with("20"), as.numeric)) %>% 
  pivot_longer("2000":"2017", 
               names_to = "time", 
               values_to = "trade_union_density") %>% 
  select(country, time, trade_union_density) %>% 
   mutate(date = make_date(time)) %>% 
  select(-time)
```

```{r}
wages <- wages %>% 
  filter(location %in% developed_codes) %>% 
  select(location, time, value) %>% 
  rename("avg_wage" = "value") %>% 
   mutate(date = make_date(time)) %>% 
  select(-time)
```

```{r}
#choose one variable to represent tech adoption overall
unique(tech_adoption$variable)

tech_adoption <- tech_adoption %>% 
  pivot_longer("Australia":"United States", names_to = "country", 
               values_to = "industrial_robots") %>% 
  filter(Variable == "industrial robots" & country %in% developed_countries |
           country == "United Kingdom") %>% 
  replace(is.na(.), 0) %>% 
  clean_names() %>% 
   mutate(date = make_date(year)) %>% 
  select(-year)
```
```{r}
unemployment <- unemployment %>% 
  filter(country_code %in% developed_codes) %>% 
  pivot_longer("1960":"2021", names_to = "date", values_to = "unemployment_pc") %>% 
  select(country_code, date, unemployment_pc) %>% 
   mutate(date = make_date(date))
```

```{r}
business_ease <- business_ease %>% 
  filter(economy %in% developed_countries | economy == "United Kingdom") %>% 
  select(economy, global_rank) %>% 
  rename("ease_of_business_rank" = "global_rank" )

business_ease <- data.frame("date" = "2018", business_ease) %>% 
   mutate(date = make_date(date)) %>% 
  mutate(ease_of_business_rank = as.factor(ease_of_business_rank))
```
```{r}
openness <- openness %>% 
  filter(location %in% developed_codes) %>% 
  select(location, time, value) %>% 
  rename("int_trade_pc_gdp" = "value") %>% 
   mutate(date = make_date(time)) %>% 
  select(-time)
```
```{r}
competitiveness <- competitiveness %>% 
  filter(Attribute == "SCORE" & Edition == "2018" & 
           `Series name` == "Global Competitiveness Index 4.0") %>% 
  pivot_longer("Angola":"South Asia", names_to = "country",
               values_to = "competitiveness_index") %>% 
  filter(country %in% developed_countries |
           country == "United Kingdom") %>% 
  select(Edition, country, competitiveness_index) %>% 
  rename("date" = "Edition") %>% 
   mutate(date = make_date(date))
```


###join and write to clean folder
```{r}
productivity <- left_join(labour_prod, multifactor_prod) %>% 
  left_join(., capital_prod) %>% 
  left_join(., adult_education)
```
```{r}
dfs = list(
  labour_prod, multifactor_prod, capital_prod, adult_education
)

purrr::reduce(dfs, left_join)
```


```{r}
productivity <- productivity %>% 
  mutate(development_flag = case_when(
    location != "GBR" ~ "developed",
    TRUE ~ "UK"
  ))

unique(productivity$development_flag)
```


```{r}
write_csv(productivity, "productivity.csv")
```


