---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(leaps)
library(modelr)
library(GGally)
library(glmulti)
```

```{r}
tfp_growth <- read_csv("clean_data/productivity_factors.csv")
```

```{r}
tfp_growth <- tfp_growth %>% 
  dplyr::select(- c(gdp_hr_worked, capital_services_pc_growth, location, date)) %>% 
  mutate(across(where(is.character), as.numeric))
```

```{r}
tfp_growth <- tfp_growth %>% 
  mutate(log_transport_investment_eur = log(transport_investment_eur),
         log_int_trade_pc_gdp = log(int_trade_pc_gdp))
```
```{r}
n_data <- nrow(tfp_growth)
test_index <- sample(1:n_data, size = n_data*0.2)
test <- slice(tfp_growth, test_index)
tfp_growth <- slice(tfp_growth, -test_index)
```


```{r}
glmulti_tfp <- glmulti(
  multifactor_prod_agrwth ~ ., 
  data = tfp_growth,
  level = 2, 
  minsize = 0,
  maxsize = -1,
  marginality = TRUE,
  method = "g",
  crit = bic, 
  plotty = FALSE,
  report = TRUE,
  confsetsize = 100,
  fitfunction = lm 
)
```

```{r}
best_model <- lm(multifactor_prod_agrwth~1+adult_education_pc+avg_wage+trade_union_density+transport_investment_eur+unemployment_pc+r_and_d_spending_pc+log_transport_investment_eur+log_int_trade_pc_gdp+trade_union_density:adult_education_pc+trade_union_density:avg_wage+unemployment_pc:transport_investment_eur+r_and_d_spending_pc:adult_education_pc+r_and_d_spending_pc:avg_wage+log_transport_investment_eur:adult_education_pc, data = tfp_growth)
```

```{r}
summary(best_model)
```

```{r}
basic_model <- lm(multifactor_prod_agrwth~1+adult_education_pc+avg_wage+trade_union_density+transport_investment_eur+unemployment_pc+r_and_d_spending_pc+log_transport_investment_eur+log_int_trade_pc_gdp, data = tfp_growth)
```

```{r}
library(relaimpo)
calc.relimp(basic_model, type = "lmg", rela = TRUE)
```

